const books = [
  {
    "id": 1,
    "imgLink": "https://m.media-amazon.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_FMjpg_UX1000_.jpg",
    "title": "The Great Gatsby",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "F. Scott Fitzgerald",
    "price": 499,
    "discountedPrice": 399,
    "discountPercentage": 20,
    rating: 4,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 2,
    "imgLink": "https://m.media-amazon.com/images/I/713jIoMO3UL._AC_UF1000,1000_QL80_.jpg",
    "title": "Sapiens: A Brief History of Humankind",
    "category": "Non-Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Yuval Noah Harari",
    "price": 799,
    "discountedPrice": 599,
    "discountPercentage": 25,
    rating: 4,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 3,
    "imgLink": "https://m.media-amazon.com/images/I/81Ls+SBCLiL._AC_UF1000,1000_QL80_.jpg",
    "title": "Atomic Habits",
    "category": "Self Help",
    "binding": "Hard Cover",
    "language": "English",
    "author": "James Clear",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    rating: 3,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 4,
    "imgLink": "https://m.media-amazon.com/images/I/81gepf1eMqL._AC_UF1000,1000_QL80_.jpg",
    "title": "To Kill a Mockingbird",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Harper Lee",
    "price": 499,
    "discountedPrice": 349,
    "discountPercentage": 30,
    rating: 2,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 5,
    "imgLink": "https://m.media-amazon.com/images/I/71-4MkLN5jL._AC_UF1000,1000_QL80_.jpg",
    "title": "Educated: A Memoir",
    "category": "Non-Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Tara Westover",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    rating: 5,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 6,
    "imgLink": "https://m.media-amazon.com/images/I/61Ij8nLooNL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Power of Now",
    "category": "Self Help",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Eckhart Tolle",
    "price": 599,
    "discountedPrice": 479,
    "discountPercentage": 20,
    rating: 4,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 7,
    "imgLink": "https://m.media-amazon.com/images/I/612ADI+BVlL._AC_UF1000,1000_QL80_.jpg",
    "title": "1984",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "George Orwell",
    "price": 649,
    "discountedPrice": 519,
    "discountPercentage": 20,
    rating: 3,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 8,
    "imgLink": "https://m.media-amazon.com/images/I/81coyP8S-ZL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Immortal Life of Henrietta Lacks",
    "category": "Non-Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Rebecca Skloot",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    rating: 1,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 9,
    "imgLink": "https://m.media-amazon.com/images/I/71t4GuxLCuL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Subtle Art of Not Giving a F*ck",
    "category": "Self Help",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Mark Manson",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    rating: 2,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 10,
    "imgLink": "https://m.media-amazon.com/images/I/91fDvMK+aEL._AC_UF1000,1000_QL80_.jpg",
    "title": "Pride and Prejudice",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Jane Austen",
    "price": 499,
    "discountedPrice": 349,
    "discountPercentage": 30,
    rating: 2,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 11,
    "imgLink": "https://m.media-amazon.com/images/I/81dDwAzxtrL._AC_UF1000,1000_QL80_.jpg",
    "title": "Becoming",
    "category": "Non-Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Michelle Obama",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    rating: 3,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 12,
    "imgLink": "https://m.media-amazon.com/images/I/71AdHA+qqwL._AC_UF1000,1000_QL80_.jpg",
    "title": "Think and Grow Rich",
    "category": "Self Help",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Napoleon Hill",
    "price": 599,
    "discountedPrice": 479,
    "discountPercentage": 20,
    rating: 3,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 13,
    "imgLink": "https://cdn.britannica.com/94/181394-050-2F76F7EE/Reproduction-cover-edition-The-Catcher-in-the.jpg",
    "title": "The Catcher in the Rye",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "J.D. Salinger",
    "price": 649,
    "discountedPrice": 519,
    "discountPercentage": 20,
    rating: 4,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 14,
    "imgLink": "https://m.media-amazon.com/images/I/71TYHByzngL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Wright Brothers",
    "category": "Non-Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "David McCullough",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    rating: 4,
    inCart: false,
    cartQuantity: 0
  },
  {
    "id": 15,
    "imgLink": "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    "title": "How to Win Friends and Influence People",
    "category": "Self Help",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Dale Carnegie",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    rating: 4,
    inCart: false,
    cartQuantity: 0
  }
]
export default books