const books = [
  {
    "id": 1,
    "imgLink": "https://m.media-amazon.com/images/M/MV5BMTkxNTk1ODcxNl5BMl5BanBnXkFtZTcwMDI1OTMzOQ@@._V1_FMjpg_UX1000_.jpg",
    "title": "The Great Gatsby",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "F. Scott Fitzgerald",
    "price": 499,
    "discountedPrice": 399,
    "discountPercentage": 20,
    rating:4
  },
  {
    "id": 2,
    "imgLink": "https://m.media-amazon.com/images/I/713jIoMO3UL._AC_UF1000,1000_QL80_.jpg",
    "title": "Sapiens: A Brief History of Humankind",
    "category": "Non-Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Yuval Noah Harari",
    "price": 799,
    "discountedPrice": 599,
    "discountPercentage": 25,
    rating:4
  },
  {
    "id": 3,
    "imgLink": "https://m.media-amazon.com/images/I/81Ls+SBCLiL._AC_UF1000,1000_QL80_.jpg",
    "title": "Atomic Habits",
    "category": "Self-Help",
    "binding": "Hard Cover",
    "language": "English",
    "author": "James Clear",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    rating:3
  },
  {
    "id": 4,
    "imgLink": "https://m.media-amazon.com/images/I/81gepf1eMqL._AC_UF1000,1000_QL80_.jpg",
    "title": "To Kill a Mockingbird",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Harper Lee",
    "price": 499,
    "discountedPrice": 349,
    "discountPercentage": 30,
    rating:2
  },
  {
    "id": 5,
    "imgLink": "https://m.media-amazon.com/images/I/71-4MkLN5jL._AC_UF1000,1000_QL80_.jpg",
    "title": "Educated: A Memoir",
    "category": "Non-Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Tara Westover",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    rating:5
  },
  {
    "id": 6,
    "imgLink": "https://m.media-amazon.com/images/I/61Ij8nLooNL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Power of Now",
    "category": "Self-Help",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Eckhart Tolle",
    "price": 599,
    "discountedPrice": 479,
    "discountPercentage": 20,
    rating:4
  },
  {
    "id": 7,
    "imgLink": "https://m.media-amazon.com/images/I/612ADI+BVlL._AC_UF1000,1000_QL80_.jpg",
    "title": "1984",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "George Orwell",
    "price": 649,
    "discountedPrice": 519,
    "discountPercentage": 20,
    rating:3
  },
  {
    "id": 8,
    "imgLink": "https://m.media-amazon.com/images/I/81coyP8S-ZL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Immortal Life of Henrietta Lacks",
    "category": "Non-Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Rebecca Skloot",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    rating:0.1
  },
  {
    "id": 9,
    "imgLink": "https://m.media-amazon.com/images/I/71t4GuxLCuL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Subtle Art of Not Giving a F*ck",
    "category": "Self-Help",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Mark Manson",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    rating:2
  },
  {
    "id": 10,
    "imgLink": "https://m.media-amazon.com/images/I/91fDvMK+aEL._AC_UF1000,1000_QL80_.jpg",
    "title": "Pride and Prejudice",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Jane Austen",
    "price": 499,
    "discountedPrice": 349,
    "discountPercentage": 30,
    rating:2
  },
  {
    "id": 11,
    "imgLink": "https://m.media-amazon.com/images/I/81dDwAzxtrL._AC_UF1000,1000_QL80_.jpg",
    "title": "Becoming",
    "category": "Non-Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Michelle Obama",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    rating:3
  },
  {
    "id": 12,
    "imgLink": "https://m.media-amazon.com/images/I/71AdHA+qqwL._AC_UF1000,1000_QL80_.jpg",
    "title": "Think and Grow Rich",
    "category": "Self-Help",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Napoleon Hill",
    "price": 599,
    "discountedPrice": 479,
    "discountPercentage": 20,
    rating:0.3
  },
  {
    "id": 13,
    "imgLink": "https://cdn.britannica.com/94/181394-050-2F76F7EE/Reproduction-cover-edition-The-Catcher-in-the.jpg",
    "title": "The Catcher in the Rye",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "J.D. Salinger",
    "price": 649,
    "discountedPrice": 519,
    "discountPercentage": 20,
    rating:4
  },
  {
    "id": 14,
    "imgLink": "https://m.media-amazon.com/images/I/71TYHByzngL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Wright Brothers",
    "category": "Non-Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "David McCullough",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    rating:4
  },
  {
    "id": 15,
    "imgLink": "https://m.media-amazon.com/images/I/71vK0WVQ4rL._AC_UF1000,1000_QL80_.jpg",
    "title": "How to Win Friends and Influence People",
    "category": "Self-Help",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Dale Carnegie",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    rating:4
  },
  {
    "id": 16,
    "imgLink": "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Alchemist",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Paulo Coelho",
    "price": 399,
    "discountedPrice": 299,
    "discountPercentage": 25,
    "rating": 5
  },
  {
    "id": 17,
    "imgLink": "https://m.media-amazon.com/images/I/81JJPDNlxSL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Silent Patient",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Alex Michaelides",
    "price": 599,
    "discountedPrice": 479,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 18,
    "imgLink": "https://m.media-amazon.com/images/I/81e+mSqZvnL._AC_UF1000,1000_QL80_.jpg",
    "title": "Where the Crawdads Sing",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Delia Owens",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 19,
    "imgLink": "https://m.media-amazon.com/images/I/71vWnStCnEL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Girl on the Train",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Paula Hawkins",
    "price": 649,
    "discountedPrice": 519,
    "discountPercentage": 20,
    "rating": 3
  },
  {
    "id": 20,
    "imgLink": "https://m.media-amazon.com/images/I/B1eAVSHxJ4L._AC_UF1000,1000_QL80_.jpg",
    "title": "Circe",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Madeline Miller",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 21,
    "imgLink": "https://m.media-amazon.com/images/I/815D5sneiNL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Night Circus",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Erin Morgenstern",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    "rating": 5
  },
  {
    "id": 22,
    "imgLink": "https://m.media-amazon.com/images/I/71ud9Tcj5YL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Goldfinch",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Donna Tartt",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 23,
    "imgLink": "https://m.media-amazon.com/images/I/71abcXUrY5L._AC_UF1000,1000_QL80_.jpg",
    "title": "The Testaments",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Margaret Atwood",
    "price": 749,
    "discountedPrice": 599,
    "discountPercentage": 20,
    "rating": 0.3
  },
  {
    "id": 24,
    "imgLink": "https://m.media-amazon.com/images/I/71D6WnPlZKL._AC_UF1000,1000_QL80_.jpg",
    "title": "Normal People",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Sally Rooney",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    "rating": 0.4
  },
  {
    "id": 25,
    "imgLink": "https://m.media-amazon.com/images/I/81pJ1u3UOML._AC_UF1000,1000_QL80_.jpg",
    "title": "Little Fires Everywhere",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Celeste Ng",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    "rating": 5
  },
  {
    "id": 26,
    "imgLink": "https://m.media-amazon.com/images/I/81lfY0CFyaL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Tattooist of Auschwitz",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Heather Morris",
    "price": 599,
    "discountedPrice": 479,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 27,
    "imgLink": "https://m.media-amazon.com/images/I/41LvfWGfleL.jpg",
    "title": "Big Little Lies",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Liane Moriarty",
    "price": 649,
    "discountedPrice": 519,
    "discountPercentage": 20,
    "rating": 3
  },
  {
    "id": 28,
    "imgLink": "https://m.media-amazon.com/images/I/91TscA6252L._AC_UF1000,1000_QL80_.jpg",
    "title": "The Dutch House",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Ann Patchett",
    "price": 799,
    "discountedPrice": 639,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 29,
    "imgLink": "https://m.media-amazon.com/images/I/81Ww1KGS3iL._AC_UF1000,1000_QL80_.jpghttps://m.media-amazon.com/images/I/81Ww1KGS3iL._AC_UF1000,1000_QL80_.jpg",
    "title": "An American Marriage",
    "category": "Fiction",
    "binding": "Hard Cover",
    "language": "English",
    "author": "Tayari Jones",
    "price": 699,
    "discountedPrice": 559,
    "discountPercentage": 20,
    "rating": 4
  },
  {
    "id": 30,
    "imgLink": "https://m.media-amazon.com/images/I/81R2jFIqpoL._AC_UF1000,1000_QL80_.jpg",
    "title": "The Nightingale",
    "category": "Fiction",
    "binding": "Soft Cover",
    "language": "English",
    "author": "Kristin Hannah",
    "price": 899,
    "discountedPrice": 719,
    "discountPercentage": 20,
    "rating": 5
  }
]
export default books